sudo: true
language: java
git:
  depth: 1
services:
- docker
env:
  global:
    secure: SesDrneGcplyl9AIrnLt8ZB86lQAIgujV+LNo4FiTNkTxM9paIfObmYdBimEToXAyydRRYZQaBpEEeebB6B4sJN2YQK50HT8WS3jBbD5CRmWy7a2YMF24AWxHm8aXOm2EQtBalf3IwvMuDTGh3fjeU9ZWuM8JIit05eKikNNEBu8hsIipVudguwR1nlmEGdaVmiP9b8mQrbPQevFd5HrRc2I0U4CcStxd6ABn2u34qv/BACmQkZYv9ffaOEyo4LEaCm8jW3VdrofMXENl/iU4hpnVtKZsk+ifpV6K8JyIYkGcEnXeQvTbpJyA7c0YIBi3nWJH3kwMgta1AcaoZNtP3oh2AerATfVv3Or1cfXLlxMR08+hGE+fZFwazuVtE40FgkM/O2H3CBT6oqCqmPkG9462D2D4SpQvYNrvz9QW0vlwaQCQ256uKUbjHsQRFkfuSZjTAyERaWJYJ4uLZm1jqqt2Ex+CQdY0XXXV2C4MXcDBFxRII1be/IOjzQxOmLNQdfBI1FX0joW6WfcLPG3xfezdGuUmgZAKejHhEQLCsEpUrRm4YZVSKaFtMeb3tN2bQQhjvPXMfwhssEA2yLUspg9Srd/mMHcmo4yuz1ghxDs1KgWhLB7teiNPXKgOWGJqD5cTrXnugDFkdUbzLmpRYO/GMnlqd5kxRUuUpjI438=
script: docker run -v $(pwd):/workspace/_override -v $(pwd)/_site:/workspace/_site
  mrduguo/adoc-site-builder
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_T"
  keep-history: true
  local-dir: _site
